networks:
    main_network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.0.0/24

services:
    geth:
        image: ethereum/client-go:stable
        container_name: geth
        restart: unless-stopped
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 30s
        volumes:
            - ../data/geth:/root/.ethereum
            - ../data/jwtsecret:/data/jwtsecret
        command: >
            --mainnet
            --datadir /root/.ethereum

            --http
            --http.addr 0.0.0.0
            --http.port 8545
            
            --metrics
            --metrics.addr 0.0.0.0
            --metrics.port 6060

            --cache 2048
            --maxpeers 30
            --authrpc.addr 0.0.0.0
            --authrpc.port 8551
            --authrpc.vhosts 0.0.0.0
            --authrpc.jwtsecret /data/jwtsecret
        expose:
            - "6060"
        ports:
            - "8545:8545"
            # - "30303:30303"
            # - 30303:30303/udp
            # - "8546:8546"
        networks:
            main_network:
                ipv4_address: 172.16.0.10

    beacon_node:
        image: chainsafe/lodestar:next
        restart: always
        
        volumes:
            - ../data/lodestar:/root/.lodestar
            - ../data/lodestar/logs:/logs
            - ../data/jwtsecret:/jwtsecret
        expose:
            - "8008"
        ports:
            - "9000:9000"
        command: >
            beacon
            --dataDir /root/.lodestar
            --jwt-secret /jwtsecret
            
            --rest
            --rest.address 0.0.0.0
            --rest.namespace "*"

            --metrics
            --metrics.address 0.0.0.0
            --metrics.port 8008
            
            --logFile /logs/beacon.log
            --logFileLevel debug
            --logFileDailyRotate 5

            --execution.urls http://172.16.0.10:8551
            --checkpointSyncUrl=https://beaconstate-mainnet.chainsafe.io
        
        environment:
            NODE_OPTIONS: --max-old-space-size=8192
        networks:
            main_network:
                ipv4_address: 172.16.0.11
