networks:
    main_network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.0.0/24

services:
    geth:
        image: ethereum/client-go:stable
        container_name: geth
        restart: unless-stopped
        volumes:
            - ../data/geth:/root/.ethereum
            - ../data/jwtsecret:/data/jwtsecret
        command: >
            --mainnet
            --datadir /root/.ethereum
            --http
            --cache 2048
            --maxpeers 30
            --authrpc.addr 0.0.0.0
            --authrpc.port 8551
            --authrpc.vhosts 0.0.0.0
            --authrpc.jwtsecret /data/jwtsecret
            --bootnodes enode://d860a01f9722d78051619d1e2351aba3f43f943f6f00718d1b9baa4101932a1f5011f16bb2b1bb35db20d6fe28fa0bf09636d26a87d31de9ec6203eeedb1f666@18.138.108.67:30303,enode://22a8232c3abc76a16ae9d6c3b164f98775fe226f0917b0ca871128a74a8e9630b458460865bab457221f1d448dd9791d24c4e5d88786180ac185df813a68d4de@3.209.45.79:30303,enode://2b252ab6a1d0f971d9722cb839a42cb81db019ba44c08754628ab4a823487071b5695317c8ccd085219c3a03af063495b2f1da8d18218da2d6a82981b45e6ffc@65.108.70.101:30303,enode://4aeb4ab6c14b23e2c4cfdce879c04b0748a20d8e9b59e25ded2a08143e265c6c25936e74cbc8e641e3312ca288673d91f2f93f8e277de3cfa444ecdaaf982052@157.90.35.166:30303
        ports:
            - 30303:30303
            - 30303:30303/udp
            - 8545:8545
            - 8546:8546
        networks:
            main_network:
                ipv4_address: 172.16.0.10

    lodestar:
        image: chainsafe/lodestar:latest
        container_name: lodestar
        restart: unless-stopped
        volumes:
            - ../data/lodestar:/root/.lodestar
            - ../data/lodestar/logs:/logs
            - ../data/jwtsecret:/jwtsecret
        command: >
            beacon
            --dataDir /root/.lodestar
            --rest
            --execution.urls http://172.16.0.10:8551
            --rest.address 0.0.0.0
            --rest.namespace '*'
            --metrics
            --logFile /logs/beacon.log
            --logFileLevel debug
            --logFileDailyRotate 5
            --jwt-secret /jwtsecret
            --checkpointSyncUrl=https://beaconstate-mainnet.chainsafe.io
        environment:
            NODE_OPTIONS: --max-old-space-size=8192
        networks:
            main_network:
                ipv4_address: 172.16.0.11
