networks:
    services_main_network:
        external: true

services:
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        restart: unless-stopped
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 30s
        ports:
            - "9090:9090"
        volumes:
            - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
            - "./prometheus/entrypoint.sh:/etc/prometheus/entrypoint.sh"
        entrypoint: ["/etc/prometheus/entrypoint.sh"]
        command: >
            --config.file=/etc/prometheus/prometheus.yml
            --storage.tsdb.path=/prometheus

        networks:
            services_main_network:
                ipv4_address: 172.16.0.20

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        restart: unless-stopped
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 30s
        ports:
            - "3000:3000"
        volumes:
            - "./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml"
            - "./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml"
            - "./grafana/dashboards:/dashboards"
        environment:
            PROMETHEUS_URL: ${PROMETHEUS_URL}
            # INFLUXDB_URL: ${INFLUXDB_URL}

            DS_PROMETHEUS: prometheus
            DS_INFLUXDB: influxdb

            DASHBOARDS_DIR: "/dashboards"

            GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
        command: >
            --homepath=/usr/share/grafana
            --packaging=docker
            cfg:default.paths.data=/var/lib/grafana
        depends_on:
            - prometheus
        networks:
            services_main_network:
                ipv4_address: 172.16.0.21

    # influxdb:
    #     image: influxdb:1.8
    #     container_name: influxdb
    #     restart: unless-stopped
    #     deploy:
    #         restart_policy:
    #             condition: on-failure
    #             delay: 5s
    #             max_attempts: 3
    #             window: 30s
    #     ports:
    #         - "8086:8086"
    #     volumes:
    #         - influxdb:/var/lib/influxdb
    #     environment:
    #         INFLUXDB_DB: your_database_name
    #         INFLUXDB_ADMIN_USER: your_admin_user
    #         INFLUXDB_ADMIN_PASSWORD: your_admin_password
    #         DS_INFLUXDB: ${DS_INFLUXDB}
    #     networks:
    #         services_main_network:
    #             ipv4_address: 172.16.0.22

volumes:
    prometheus:
#   logs:
#   grafana:
#   grafana-dashboards: