global:
  scrape_interval: 5s
  scrape_timeout: 5s

scrape_configs:
  - job_name: geth
    scrape_interval: 15s
    scrape_timeout: 5s
    metrics_path: /debug/metrics/prometheus
    scheme: http
    static_configs:
      - targets:
        - 172.16.0.10:6060

  - job_name: lodestar
    scrape_interval: 15s
    scrape_timeout: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
        - 172.16.0.11:8008
